<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_043802 - Columbus City Schools District</name>
   <tag></tag>
   <elementGuidId>532a49d2-c304-46ef-ab68-78d8f16a2add</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='searchResult83424']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchResult83424</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ebc9ad72-a234-4336-bdfc-391c249ef714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchResult83424</value>
      <webElementGuid>5a76ba00-0e55-4096-8d04-e010c543415f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/overview/83424?appPeriodKey=18502&amp;orgIrn=043802&amp;fiscalYear=2024</value>
      <webElementGuid>80db25be-14e5-4ce3-99ce-b0c3ab8398b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>043802 - Columbus City Schools District</value>
      <webElementGuid>dedad0ea-a7c7-44ed-add9-1b623816ef9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResult83424&quot;)</value>
      <webElementGuid>17b32f36-031d-48f2-89f3-cd4351e86e96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='searchResult83424']</value>
      <webElementGuid>d361e01a-a57c-4c49-9faf-a42bf7656c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'043802 - Columbus City Schools District')]</value>
      <webElementGuid>628e9e07-3dcf-4b61-87dd-4ae97d254abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compliant'])[7]/following::a[1]</value>
      <webElementGuid>d99977ff-7be8-4ba7-8a0e-e53e79b489be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In Progress'])[7]/following::a[1]</value>
      <webElementGuid>c4bcd1ed-bbd5-4311-83cb-066aca628de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESSER FY 2024'])[7]/preceding::a[1]</value>
      <webElementGuid>cc3c5250-0d50-4eed-bf16-965c92412682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Started'])[5]/preceding::a[1]</value>
      <webElementGuid>2cd14347-7463-4138-ba6d-9d7376442bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='043802 - Columbus City Schools District']/parent::*</value>
      <webElementGuid>dba3783a-54b1-47c6-bce1-ec2ca6a0f0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/overview/83424?appPeriodKey=18502&amp;orgIrn=043802&amp;fiscalYear=2024')]</value>
      <webElementGuid>790c2902-550c-4116-ae79-fb74ee37542e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/a</value>
      <webElementGuid>1e8ed02e-eed7-41dd-b6a8-9f914bc768e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'searchResult83424' and @href = '/overview/83424?appPeriodKey=18502&amp;orgIrn=043802&amp;fiscalYear=2024' and (text() = '043802 - Columbus City Schools District' or . = '043802 - Columbus City Schools District')]</value>
      <webElementGuid>58ad4ebc-3777-4896-be82-8041782982db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
