<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building IRNName_building</name>
   <tag></tag>
   <elementGuidId>dff39e46-b7b4-4930-9cae-bc7ec0f2924b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'building' and @name = 'building']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='building']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3adb4c16-8e8f-4047-8ef6-345bc852ad38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ad5cfaf8-48c2-47d0-9c0a-1ea779eb2b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca18a178-720f-42e3-b9c5-114e70986602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeaheadoptionslimit</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7eae8532-c9e4-4294-8d54-e3276a6436ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeaheadwaitms</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>9308596e-8785-4a8a-9b35-0fb823a37793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>2d5f5d62-fb85-4ebe-bdbb-f9a8de8e46bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>1b7e00ef-166b-446b-a442-0134c684cab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead-min-length</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>17c98d39-30a1-4752-8ee4-7d648495325c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead-wait-ms</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>101ebde0-f783-4d86-9ded-0e5893c93f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead-options-limit</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>29735a2e-9628-46d5-bf69-25d989e3fc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead-option-field</name>
      <type>Main</type>
      <value>fullName</value>
      <webElementGuid>13a4a2ee-71f2-4d56-9c47-11c1d9299233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead-async</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c1d982d-ae7f-49d7-9209-4f5e70178b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ohio-field-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>fcc0c29f-3e36-428d-ad48-310e9c22a757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>building</value>
      <webElementGuid>a0562f55-b774-4fd9-90a1-57b270d2ed96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>building</value>
      <webElementGuid>f2740192-dcec-4654-b8a0-594e4f00c85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;building&quot;)</value>
      <webElementGuid>7ab726e7-94ff-424a-a3db-acdae0f159d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='building']</value>
      <webElementGuid>ce07e60f-22b4-48c2-a60e-aefc3fb2be46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/app-search-container/div/div/app-search-form/div/div/eas-ui-lib-card/div/div/div/div/div/app-autocomplete-filter/eas-ui-lib-form-group/label/input</value>
      <webElementGuid>0ad949cb-1fc9-401f-a440-018c5330b333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/app-autocomplete-filter/eas-ui-lib-form-group/label/input</value>
      <webElementGuid>51be1ad1-2ef4-4072-a435-2e38c5f0d055</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
