<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please provide additional information a_12ad7b</name>
   <tag></tag>
   <elementGuidId>89e017ee-edf8-42f8-ba89-dab13d4815c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#questtext0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='questtext0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ef85e40-9e14-4fac-a2df-c2f88f43f158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>question-text</value>
      <webElementGuid>7a778a5f-c82a-4a03-8479-e32ab3580ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>questtext0</value>
      <webElementGuid>b4972910-65f9-4c51-a8d6-1483c3f73123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please provide additional information about the student's educational programming.</value>
      <webElementGuid>4d56282c-ac98-4562-8591-269a0d02f09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;questtext0&quot;)</value>
      <webElementGuid>61313569-2b50-4ec4-a204-3cabb27c92ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='questtext0']</value>
      <webElementGuid>d5a4de27-45fe-4703-8e9c-965facf279a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID: Question'])[1]/following::div[2]</value>
      <webElementGuid>6eabcee0-0791-4447-b36a-8c20577b4b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a required question'])[1]/following::div[2]</value>
      <webElementGuid>b4b9b3b2-b353-40e5-9130-c82ddeb2ec44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::div[4]</value>
      <webElementGuid>c55f5382-f449-4e18-82b4-5a01db40666c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::div[4]</value>
      <webElementGuid>149bd2e0-5107-4c04-ad3a-340910965190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div</value>
      <webElementGuid>80eb68f6-856b-4907-bcff-3694b16abb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'questtext0' and (text() = concat(&quot;Please provide additional information about the student&quot; , &quot;'&quot; , &quot;s educational programming.&quot;) or . = concat(&quot;Please provide additional information about the student&quot; , &quot;'&quot; , &quot;s educational programming.&quot;))]</value>
      <webElementGuid>961888a9-43a2-4739-b29d-c4a06b43c417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
