<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please choose the reason why an Emerg_c56b4c</name>
   <tag></tag>
   <elementGuidId>d762a4ec-6014-40fa-8745-cc9040dd1b4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#14910601</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='14910601']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4b961e1-c9a9-4f64-8e83-6a806f65adf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>57f3258f-fabf-4647-8c8b-8bcb5beee752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>14910601</value>
      <webElementGuid>2dfcae2a-2557-45bb-abdf-204dc02c24ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5badad05-5e93-483d-9489-ce37e885e7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;14910601&quot;)</value>
      <webElementGuid>6b42abd6-8cef-4f4b-8e1f-dcd2cb99b295</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='14910601']</value>
      <webElementGuid>f69ea04a-bccd-4628-81bd-d8a6df637b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>27ed3a2b-c600-4b2d-a91f-57589b9ad804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '14910601']</value>
      <webElementGuid>9873ccb2-5585-424c-afd1-9f93055b1d4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
