<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Listening_14910802</name>
   <tag></tag>
   <elementGuidId>e1a4cc12-94eb-46e5-a23b-03735406ea94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#14910802</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='14910802']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff0ce93c-d1ab-46c8-bf36-2c6534e07e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ebf441bc-d131-4246-8914-06e43c2a8f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>14910802</value>
      <webElementGuid>c37f70de-4d28-4b81-92fc-48cddd783b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>32288959-9a3c-417c-ab00-e8a4aad94ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;14910802&quot;)</value>
      <webElementGuid>75069624-91c4-4cd0-a22f-75b5c3f4364a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='14910802']</value>
      <webElementGuid>ed63afe7-d880-4880-b190-9538fc92b1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/eas-survey-lib-answer/div/span[2]/input</value>
      <webElementGuid>8e5f18c9-a62d-49e0-8c77-afa3843f7dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '14910802']</value>
      <webElementGuid>79ae3e05-9413-4c96-8241-45af291dccce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
