<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_American History_14911702</name>
   <tag></tag>
   <elementGuidId>69b73347-6434-4ae8-9853-85b27b53280e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#14911702</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='14911702']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28e10f0d-8e1b-4d54-a8c1-abaeb9bcd5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>164bffe3-1bf2-41c4-8543-b00ee529213d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>14911702</value>
      <webElementGuid>817fe579-7a4c-47d1-981e-16d200028c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f73ed32b-fba6-4565-abf1-979905c72293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;14911702&quot;)</value>
      <webElementGuid>c5bcee93-d3f5-47b7-a041-610dea94fa17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='14911702']</value>
      <webElementGuid>6f4a86d0-9072-48df-9037-f0a2c8829b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/eas-survey-lib-answer/div/span[2]/input</value>
      <webElementGuid>957c4465-a1d4-4bd6-8b5d-cf0b93be8b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '14911702']</value>
      <webElementGuid>600e5e96-007c-4a61-a6ae-f2465fbe9a80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
