<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Question_100</name>
   <tag></tag>
   <elementGuidId>ca79f8d7-311a-42e4-bd15-c121374e5cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='100']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eebe91a3-86e2-4c47-bfd2-bf1ba0cb3d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ce419f9c-3861-4491-9a4f-9547e83b31a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>295867e0-94ec-405b-837d-30aa535209f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>95decff3-ab9c-4193-8dbc-76c27e8e70ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;100&quot;)</value>
      <webElementGuid>34a1da3e-5cbd-4702-8b0c-4925031c0d17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='100']</value>
      <webElementGuid>ee8685ca-a2c4-44ac-b8b3-947809bdf781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/input</value>
      <webElementGuid>197fd923-2dc0-44a6-82e9-1c806fed1285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '100']</value>
      <webElementGuid>b07e7618-381c-48bd-9fd2-db120cba1ce8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
