<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Grade 4 Math_14911303</name>
   <tag></tag>
   <elementGuidId>df6fec07-554e-48a0-af5f-553e3476455a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#14911303</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='14911303']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31e007ee-d98e-4302-af8e-78b2a721d0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>607bae8f-6231-4240-adda-ab7bad66763f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>14911303</value>
      <webElementGuid>e134bd78-b85c-48b5-a8d9-a9218ebcf989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>8228cddb-21b5-4e77-a7f8-5292cab19dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;14911303&quot;)</value>
      <webElementGuid>ee325446-0e2a-41f3-b82b-8db770aeda1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='14911303']</value>
      <webElementGuid>b5d74e2b-94dc-44ac-88d6-76b8f59b817a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/input</value>
      <webElementGuid>de870298-de78-42d0-af63-686ec38675f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '14911303']</value>
      <webElementGuid>b959e0f1-6583-43b9-88cd-afb55f89974e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
