<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TEST TYPE  MATHEMATICS_14910101</name>
   <tag></tag>
   <elementGuidId>ca898f78-0bc8-4baa-bd1b-0eac72cc71a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#14910101</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='14910101']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3d9ba0b-c799-47f9-9443-90961b21936c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>099abe98-b485-4412-b7fe-95d822b89212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>14910101</value>
      <webElementGuid>8569b8e2-f45e-43cf-9af1-49021f5e4de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5935a272-f693-4b94-bc56-befbe2fe89ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;14910101&quot;)</value>
      <webElementGuid>60dd4413-ff73-4e57-bbec-95b062e90aa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='14910101']</value>
      <webElementGuid>58f87d57-0f03-4cf5-af9d-cf086986bae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/eas-survey-lib-answer/div/span/input</value>
      <webElementGuid>d6096507-f05e-4b61-b228-f38b12bd3e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '14910101']</value>
      <webElementGuid>be905de2-784e-4569-9963-9818ea1c7872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
