<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_District IRNName_district</name>
   <tag></tag>
   <elementGuidId>6392721b-8588-4516-9f42-27c73d8efa0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'district' and @name = 'district']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='district']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#district</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86992fe2-085c-4dc5-ac74-1a7149a31872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f2873fd2-74aa-4d33-a1b2-f3877bab4afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4400384-d7fe-4bf0-9d04-ea93045aee9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeaheadoptionslimit</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7cdd86bd-7a2b-44b5-a46c-3b8a173e6da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeaheadwaitms</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>cdfa066f-3cf8-41bf-b71b-a4d00637e77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>district</value>
      <webElementGuid>f89f3a42-7618-444a-9b95-7b7d6f49cf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>district</value>
      <webElementGuid>2e6ff1f1-c6b6-46d4-99d1-b79cf7d29f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ohio-field-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>50a5f80d-c99e-4197-9bbf-d9f17b2c924b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6587d37d-4147-4fcc-8470-32ab87f9789f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>d932b5f8-ca11-4e3a-bd61-6f24e78bc0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;district&quot;)</value>
      <webElementGuid>9f3b50a7-9b91-46b6-86f9-19bc8aeb9a34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='district']</value>
      <webElementGuid>c3c6b276-7e63-459e-830a-9553b462329f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c2e87240-6336-4ca8-9340-07a9890f56fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'district' and @name = 'district']</value>
      <webElementGuid>49d306f4-994b-4ca8-870c-21436b0e68d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
