<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Student gave birth immediately before_22a4cc</name>
   <tag></tag>
   <elementGuidId>47b1a733-c34f-4aa1-a304-11a53312ea08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#14910706</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='14910706']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85d108cf-a40d-4dba-9fb3-b68a7497962f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>18b89761-c82a-49b8-b785-26a0050d8fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>14910706</value>
      <webElementGuid>d54fc0e2-eb59-428d-a7c2-c62a719e2af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c84cfecc-368a-491b-96e3-c222dfbe4126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;14910706&quot;)</value>
      <webElementGuid>b31e8ca8-58f9-429b-b619-9cadc09c6c4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='14910706']</value>
      <webElementGuid>86c51a65-f781-4c1c-90b9-ca72abeff398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/input</value>
      <webElementGuid>5dd9328d-a5e9-4375-b93e-a816c1457142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '14910706']</value>
      <webElementGuid>d94cc5df-62ce-4c3a-9135-c74b95b52f90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
