<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_102</name>
   <tag></tag>
   <elementGuidId>ce7cc05d-8c81-4100-bb1a-e2084eeb22cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#102</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='102']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e21d46f9-ff05-4847-9ef2-ab0585563b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>181a18db-057a-43ac-80ec-96c9124fe181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>102</value>
      <webElementGuid>0024dbfd-6f46-48e9-b1da-841f41ada16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>659b5045-f22b-429b-a90b-5f790b4282a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/eas-core-application-container[1]/div[@class=&quot;exp-application&quot;]/div[@class=&quot;exp-content hide-spliter&quot;]/as-split[@class=&quot;as-horizontal as-pixel as-init&quot;]/as-split-area[@class=&quot;as-split-area&quot;]/div[@class=&quot;exp-panel&quot;]/div[@class=&quot;container-fluid&quot;]/app-questions-tab[1]/div[1]/div[@class=&quot;container-fluid results-section&quot;]/eas-mon-surveys-container[1]/div[1]/div[@class=&quot;container-fluid results-section&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/survey-questions-container[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;ohio-card ode-section clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/survey-questions[1]/div[@class=&quot;question-shell&quot;]/div[@class=&quot;ng-star-inserted&quot;]/eas-survey-lib-question[1]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;survey-question-legend survey-end clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;ng-star-inserted&quot;]/eas-survey-lib-answer[1]/div[@class=&quot;ng-star-inserted&quot;]/span[@class=&quot;question-answer radio-spacer ng-star-inserted&quot;]/input[@id=&quot;102&quot;]</value>
      <webElementGuid>f442a2bc-d982-47ca-ba1f-5b0891ce89bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='102']</value>
      <webElementGuid>cfd85951-aa62-4356-8116-edff8fa219d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>e3cf8a3e-1843-4352-9043-b486ad9dd2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '102']</value>
      <webElementGuid>0199979d-9b18-4414-974f-41e9223032e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
