<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_In Progress Submitted</name>
   <tag></tag>
   <elementGuidId>8c7eb4cf-2504-45c2-baf7-24032d181b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.tableRow.rowSelected.selected > td:nth-of-type(5) > div.dropdown-container > div.dropdown-div > label.ohio-select > span.ohio-select-select.fa > #surveyWorkFlowState</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='surveyWorkFlowState'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5457cfcd-0e36-4ca0-99ca-501bab95d5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sg-native-dropdown-name</value>
      <webElementGuid>8fc46e01-9210-4c2a-b04d-5818f729275a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>surveyWorkFlowState</value>
      <webElementGuid>17295655-232d-4be7-812b-c2b132c8eed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ohio-select-select-el</value>
      <webElementGuid>17522437-818a-4bcb-8aa7-cc2cacb68951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> In Progress Submitted</value>
      <webElementGuid>78e42c98-0085-46f3-8267-9fa7382a4a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/eas-core-application-container[1]/div[@class=&quot;exp-application&quot;]/div[@class=&quot;exp-content hide-spliter&quot;]/as-split[@class=&quot;as-horizontal as-pixel as-init&quot;]/as-split-area[@class=&quot;as-split-area&quot;]/div[@class=&quot;exp-panel&quot;]/div[@class=&quot;container-fluid&quot;]/app-questions-tab[1]/div[1]/div[@class=&quot;container-fluid results-section&quot;]/eas-mon-surveys-container[1]/div[1]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;ohio-card ode-section clearfix&quot;]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/eas-mon-survey-list[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 child&quot;]/eas-mon-child-survey-list[1]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/div[@class=&quot;ohio-table&quot;]/table[@class=&quot;table table-striped table-hover&quot;]/tbody[1]/tr[@class=&quot;tableRow rowSelected selected&quot;]/td[5]/div[@class=&quot;dropdown-container&quot;]/div[@class=&quot;dropdown-div&quot;]/label[@class=&quot;ohio-select&quot;]/span[@class=&quot;ohio-select-select fa&quot;]/select[@id=&quot;surveyWorkFlowState&quot;]</value>
      <webElementGuid>f55ea409-f34f-438c-84be-627e9af025eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='surveyWorkFlowState'])[2]</value>
      <webElementGuid>f8ab57b4-9360-4ad7-9541-760cf03574f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AN8765436'])[1]/following::select[1]</value>
      <webElementGuid>94d0e993-c7cf-4ad0-8c7a-2a8ac4963b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Survey'])[2]/following::select[1]</value>
      <webElementGuid>25d5f409-9a58-4d13-a0ef-0a20953c8226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Student'])[1]/preceding::select[1]</value>
      <webElementGuid>82d2491d-f8ad-4412-9dec-27a4592e4936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous 5 Results'])[1]/preceding::select[1]</value>
      <webElementGuid>f36822ac-683c-49e2-9452-08de475f9494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/div/div/label/span/select</value>
      <webElementGuid>224f08c0-6bea-4cbe-b517-8725e256f984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sg-native-dropdown-name' and @id = 'surveyWorkFlowState' and (text() = ' In Progress Submitted' or . = ' In Progress Submitted')]</value>
      <webElementGuid>333022ab-ecdf-414e-baa5-777ea04a278b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
