<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ESSER State Activities Project 1 Reporting</name>
   <tag></tag>
   <elementGuidId>59254e30-7c23-44c5-9d19-7d811687d88f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='questsection']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#questsection</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2704ccd-82b9-41b7-be03-533856f51d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>questsection</value>
      <webElementGuid>3a5059a0-60bf-4bb2-85c2-690a43e968cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section-title</value>
      <webElementGuid>813870f7-0ca3-448f-919b-1bb7e003f62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ESSER State Activities Project 1 Reporting  </value>
      <webElementGuid>4f27ae24-c73d-4151-9e8f-f3f85e4fcad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;questsection&quot;)</value>
      <webElementGuid>de240ac6-2854-47c0-a640-a38920275bb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='questsection']</value>
      <webElementGuid>80257cd9-011e-4911-8b59-1c359340a3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prev Section'])[1]/following::div[6]</value>
      <webElementGuid>53ad15ae-4845-47fb-8aad-cf64bdfb9542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FY 2024 ESSER State Activities Projects - Quarterly Data Reporting Survey'])[3]/following::div[8]</value>
      <webElementGuid>ffcbded8-82bc-40e6-a13f-a9c0c3134aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LEA'])[2]/preceding::div[2]</value>
      <webElementGuid>167fe715-ba8f-4417-8d75-fb6ebec332bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next Section'])[1]/preceding::div[3]</value>
      <webElementGuid>d048a810-fcc6-407f-884c-a771dd58f1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>6bc7fb20-dd40-4a3e-9329-0c0bb238c093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'questsection' and (text() = ' ESSER State Activities Project 1 Reporting  ' or . = ' ESSER State Activities Project 1 Reporting  ')]</value>
      <webElementGuid>11a40f0a-6ac0-4c40-861b-3a34a28f3918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
