<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_102</name>
   <tag></tag>
   <elementGuidId>d7e05d94-f36d-4988-957c-3c386ff69386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='102']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#102</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d556a04f-646a-4cd0-b71b-7380fd361f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0f87b2d3-1bec-4977-998c-b3caba228e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>102</value>
      <webElementGuid>217e6be9-2e44-4397-9010-c5eb55fbd1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>64df0881-6d44-4a88-ab11-3c416f51b602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/eas-core-application-container[1]/div[@class=&quot;exp-application&quot;]/div[@class=&quot;exp-content hide-spliter&quot;]/as-split[@class=&quot;as-horizontal as-pixel as-init&quot;]/as-split-area[@class=&quot;as-split-area&quot;]/div[@class=&quot;exp-panel&quot;]/div[@class=&quot;container-fluid&quot;]/app-questions-tab[1]/div[1]/div[@class=&quot;container-fluid results-section&quot;]/eas-mon-surveys-container[1]/div[1]/div[@class=&quot;container-fluid results-section&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/survey-questions-container[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;ohio-card ode-section clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/survey-questions[1]/div[@class=&quot;question-shell&quot;]/div[@class=&quot;ng-star-inserted&quot;]/eas-survey-lib-question[1]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;survey-question-legend survey-end clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;ng-star-inserted&quot;]/eas-survey-lib-answer[1]/div[@class=&quot;ng-star-inserted&quot;]/span[@class=&quot;question-answer radio-spacer ng-star-inserted&quot;]/input[@id=&quot;102&quot;]</value>
      <webElementGuid>bc12daf1-049c-4465-a08d-9f7e4a99734d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='102']</value>
      <webElementGuid>354d3a1b-a227-463a-9c2e-5bca373ac991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>0552dba5-cdf3-4512-8fa4-11f21af21f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '102']</value>
      <webElementGuid>d61b5257-6837-4079-bbb0-3296166267d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
