<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Approximately how much has been oblig_5756ec</name>
   <tag></tag>
   <elementGuidId>c4a342b3-d7e8-4f57-b8a0-6445388d4e63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='currencyTextBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;currencyTextBox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26798341-2dff-4988-b583-f0af83f1db90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currencyTextBox</value>
      <webElementGuid>3f793722-9074-4d65-9472-26ef4574249a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.style.height = &quot;&quot;;this.style.height = this.scrollHeight + 3+ &quot;px&quot;</value>
      <webElementGuid>936c81a1-5f47-470b-8cc0-f5ed75c91f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^-?[0-9]\d*([,]\d+)*(\.\d+)?$</value>
      <webElementGuid>b2252856-3cc4-4a03-aee1-ccad79fdb211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ohio-field-input dollar-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>62b333cd-3732-4c38-9cfd-b1c5e2f5585d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>a559ae9b-f8ef-470c-83b8-5e0dea7ce71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/eas-core-application-container[1]/div[@class=&quot;exp-application&quot;]/div[@class=&quot;exp-content hide-spliter&quot;]/as-split[@class=&quot;as-horizontal as-pixel as-init&quot;]/as-split-area[@class=&quot;as-split-area&quot;]/div[@class=&quot;exp-panel&quot;]/div[@class=&quot;container-fluid&quot;]/app-questions-tab[1]/div[1]/div[@class=&quot;container-fluid results-section&quot;]/eas-mon-surveys-container[1]/div[1]/div[@class=&quot;container-fluid results-section&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/survey-questions-container[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;ohio-card ode-section clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/survey-questions[1]/div[@class=&quot;question-shell&quot;]/div[@class=&quot;ng-star-inserted&quot;]/eas-survey-lib-question[1]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;survey-question-legend survey-end clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;survey-input-group-container ng-star-inserted&quot;]/eas-survey-lib-answer[1]/div[@class=&quot;input-grouping ng-star-inserted&quot;]/span[@class=&quot;question-answer dollar&quot;]/input[@class=&quot;form-control ohio-field-input dollar-input ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>1cf625cc-c340-46be-9d6d-646150eb3b51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='currencyTextBox']</value>
      <webElementGuid>0c5ad6cc-46bd-4cfa-8d51-725d85db013f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/eas-survey-lib-question/form/div/div/div[2]/div[3]/eas-survey-lib-answer/div/span/input</value>
      <webElementGuid>05c46a9b-76cd-41ea-aed6-ff0ba5282b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'currencyTextBox']</value>
      <webElementGuid>463edc5f-210b-4b12-a3ef-0a1014bd8128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
