<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_In Progress Completed</name>
   <tag></tag>
   <elementGuidId>f5e352a8-cdf4-40ed-854d-0f22db1f612c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='surveyWorkFlowState']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#surveyWorkFlowState</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>57a4d402-3830-410c-92fe-323b4b94f3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sg-native-dropdown-name</value>
      <webElementGuid>80740703-ac93-4ee4-a946-76a0358f553e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>surveyWorkFlowState</value>
      <webElementGuid>2275e623-008d-4cc5-8375-eaae26b389c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ohio-select-select-el</value>
      <webElementGuid>4abae2c1-1834-46f3-bc01-89165f531426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> In Progress Completed</value>
      <webElementGuid>dc492a68-b7b9-4d59-8248-c65ce536c6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/eas-core-application-container[1]/div[@class=&quot;exp-application&quot;]/div[@class=&quot;exp-content hide-spliter&quot;]/as-split[@class=&quot;as-horizontal as-pixel as-init&quot;]/as-split-area[@class=&quot;as-split-area&quot;]/div[@class=&quot;exp-panel&quot;]/div[@class=&quot;container-fluid&quot;]/app-questions-tab[1]/div[1]/div[@class=&quot;container-fluid results-section&quot;]/eas-mon-surveys-container[1]/div[1]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;ohio-card ode-section clearfix&quot;]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/eas-mon-survey-list[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;ohio-table&quot;]/table[@class=&quot;table table-stripped table-hover&quot;]/tbody[1]/tr[@class=&quot;tableRow rowSelected selected&quot;]/td[6]/div[@class=&quot;dropdown-container&quot;]/div[@class=&quot;dropdown-div&quot;]/label[@class=&quot;ohio-select&quot;]/span[@class=&quot;ohio-select-select fa&quot;]/select[@id=&quot;surveyWorkFlowState&quot;]</value>
      <webElementGuid>a5f1c527-911e-41ea-9f6c-375556b96335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='surveyWorkFlowState']</value>
      <webElementGuid>e4a7bd33-5008-4fc8-8ccd-ac7d6812c4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FY 2024 ESSER State Activities Projects - Quarterly Data Reporting Survey'])[1]/following::select[1]</value>
      <webElementGuid>8bdde754-6c17-41e5-843b-c473fcb3c8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completion Status'])[1]/following::select[1]</value>
      <webElementGuid>9d116069-f3a3-4fe3-a12a-14f6768561a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FY2024 ESSER State Activities Projects - Desk Review Survey'])[1]/preceding::select[1]</value>
      <webElementGuid>0f191777-8808-4e58-9ce8-e50e56132c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Started'])[1]/preceding::select[1]</value>
      <webElementGuid>95b40945-7620-4a5b-b055-c293ab82be8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span/select</value>
      <webElementGuid>b1ebec37-ee32-4836-9cde-87889af04586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'sg-native-dropdown-name' and @id = 'surveyWorkFlowState' and (text() = ' In Progress Completed' or . = ' In Progress Completed')]</value>
      <webElementGuid>255a27c0-c780-4454-b8eb-b0d44f8864b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
