<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_key activities_text</name>
   <tag></tag>
   <elementGuidId>0485ad9d-a2ae-4d4d-87a6-22a972399af9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2d0358c7-9ab3-43fd-9b94-84abca32473d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94901b6b-8e29-48a7-836e-bdc0b04b38b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ohio-textarea-field survey ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>bbd02e20-a592-4d98-b817-ef3168161a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b0d61515-481f-41fe-b00b-25ffc55775d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8000</value>
      <webElementGuid>b0301bd1-4061-4d3b-9485-8e7b5c9ae5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/eas-core-application-container[1]/div[@class=&quot;exp-application&quot;]/div[@class=&quot;exp-content hide-spliter&quot;]/as-split[@class=&quot;as-horizontal as-pixel as-init&quot;]/as-split-area[@class=&quot;as-split-area&quot;]/div[@class=&quot;exp-panel&quot;]/div[@class=&quot;container-fluid&quot;]/app-questions-tab[1]/div[1]/div[@class=&quot;container-fluid results-section&quot;]/eas-mon-surveys-container[1]/div[1]/div[@class=&quot;container-fluid results-section&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/survey-questions-container[1]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;ohio-card ode-section clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/survey-questions[1]/div[@class=&quot;question-shell&quot;]/div[@class=&quot;ng-star-inserted&quot;]/eas-survey-lib-question[1]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;survey-question-legend utility-active survey-end clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;ng-star-inserted&quot;]/eas-survey-lib-answer[1]/div[@class=&quot;ng-star-inserted&quot;]/label[@class=&quot;ohio-textarea&quot;]/textarea[@class=&quot;ohio-textarea-field survey ng-untouched ng-valid ng-dirty&quot;]</value>
      <webElementGuid>ce0adadb-8d38-4922-bc85-ad1eaae4f548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='text']</value>
      <webElementGuid>1e29f3b0-6c1f-48c0-9401-bf73b682bea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3dd6d250-001a-466e-a7d7-7120b6e8579b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'text']</value>
      <webElementGuid>0061c3aa-db3f-4ee4-bcbe-45563524ea72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
