<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_000556 - A Arts Academy</name>
   <tag></tag>
   <elementGuidId>c7ca4c9d-eeac-4e94-b8f0-25e27b37eb47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchResult72377</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='searchResult72377']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>879f4485-9875-4722-8331-e60580d79443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchResult72377</value>
      <webElementGuid>9d20d381-a7b1-4f4a-9e0d-4f54e66e01b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/overview/72377?appPeriodKey=12011&amp;orgIrn=000556&amp;fiscalYear=2024</value>
      <webElementGuid>0597f5ae-1284-405a-ae52-34756c1e472c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>000556 - A+ Arts Academy</value>
      <webElementGuid>a08dc79c-37b9-4986-ac50-5b2fb153d6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchResult72377&quot;)</value>
      <webElementGuid>58d73e50-2432-4db3-869f-739c839dffc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='searchResult72377']</value>
      <webElementGuid>e234c3f7-835f-4110-a0f1-6ae88fcf515d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'000556 - A+ Arts Academy')]</value>
      <webElementGuid>d5cf7086-934a-4d61-9bda-f938488f23e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultants'])[2]/following::a[1]</value>
      <webElementGuid>6cfcc31c-f0aa-4335-92f3-ff8b6209a64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sponsor'])[1]/following::a[1]</value>
      <webElementGuid>678f338c-6126-4ceb-b3d0-193318dcd343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consolidated ESEA FY 2024'])[1]/preceding::a[1]</value>
      <webElementGuid>bb1e67ee-4bba-4743-93fe-d491430a6662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In Progress'])[3]/preceding::a[1]</value>
      <webElementGuid>d287577b-8228-465e-8244-afc248ffc85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='000556 - A+ Arts Academy']/parent::*</value>
      <webElementGuid>c3a025df-afdc-4c58-b8aa-d2e7b4159dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/overview/72377?appPeriodKey=12011&amp;orgIrn=000556&amp;fiscalYear=2024')]</value>
      <webElementGuid>0e94d20a-a6d6-43b4-ae8b-713c73efac26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>af3053d0-b75c-4027-95fd-93696419936d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'searchResult72377' and @href = '/overview/72377?appPeriodKey=12011&amp;orgIrn=000556&amp;fiscalYear=2024' and (text() = '000556 - A+ Arts Academy' or . = '000556 - A+ Arts Academy')]</value>
      <webElementGuid>6bdf8a88-4e31-47bf-b8c1-0dc1cdc5fc88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
