<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Consolidated ESEA Grants</name>
   <tag></tag>
   <elementGuidId>22284dad-80ae-4e43-aa55-ddd12d378e70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#app_id_120</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='app_id_120']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ab1259d2-20f5-4aa5-8dc2-0a65960b884e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_id_120</value>
      <webElementGuid>1be7c5f4-85d9-449e-9008-17202930ee7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consolidated ESEA Grants</value>
      <webElementGuid>ef5eef36-2b27-48f9-bba2-5b4645f0face</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_id_120&quot;)</value>
      <webElementGuid>969a3ab4-8dc0-4c99-b041-e37fc6642df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='app_id_120']</value>
      <webElementGuid>7f91547d-6ed3-4265-a30e-e3597c971e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Consolidated ESEA Grants')]</value>
      <webElementGuid>00c1db00-7038-4340-81b1-c93575b1e926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Associated To'])[1]/following::a[1]</value>
      <webElementGuid>ae791f52-1e9d-4f2d-a969-6b0d47d25fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View As'])[1]/following::a[1]</value>
      <webElementGuid>b82ab315-11ac-4b8d-94c8-ae19086c22e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Education Fiscal Monitoring'])[1]/preceding::a[1]</value>
      <webElementGuid>05482a44-01b1-4b0e-ab7b-67d62b12e581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CTE Perkins Monitoring'])[1]/preceding::a[2]</value>
      <webElementGuid>90c8afe1-d2fb-4ce3-b1e7-8b9c38cf2d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Consolidated ESEA Grants']/parent::*</value>
      <webElementGuid>3e7acaa4-7d08-4ee2-8593-7c87c7cae6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>02f6deb9-b294-4fe9-aa91-a22b34414323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'app_id_120' and (text() = 'Consolidated ESEA Grants' or . = 'Consolidated ESEA Grants')]</value>
      <webElementGuid>05818053-1cee-47f1-9280-ceac364d731b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
