<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Desk Review</name>
   <tag></tag>
   <elementGuidId>d013db0a-d883-4e2c-bb7d-3d5e1f484a57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a12003cb5849-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a12003cb5849-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'a12003cb5849-0' and (text() = 'Desk Review' or . = 'Desk Review')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>abd53d35-f158-4b75-9475-b40fdbf3a7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked</value>
      <webElementGuid>4fda3ab9-3eb8-4eda-8be4-be669395b148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9ddd272b-8908-46f0-af29-8156646a0eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>554a9226-71fb-40b4-b357-4a523589c8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a12003cb5849-0</value>
      <webElementGuid>74f8ec6e-cf20-41e9-a12b-8c8c9159cb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desk Review</value>
      <webElementGuid>f63181b2-7334-407c-83f9-6075705a799e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a12003cb5849-0&quot;)</value>
      <webElementGuid>ea455a09-dfa5-4b74-af68-50f568bab788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a12003cb5849-0']</value>
      <webElementGuid>2520ac68-ea78-4e67-8bb8-24111baddf96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a12003cb5849']/div/div[2]/div</value>
      <webElementGuid>effa495a-e4e9-4fc5-83e4-1141d503b322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose ...'])[1]/following::div[5]</value>
      <webElementGuid>e2ae2fa6-c0f0-48fe-b98f-8db2093f3b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[8]</value>
      <webElementGuid>68fb5924-0659-4364-ae17-4c2a42c7385d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-site Review'])[1]/preceding::div[1]</value>
      <webElementGuid>c201620a-58df-4c59-b9be-7525d7ae50a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>326eeb0e-0683-4748-bea4-118814327249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a12003cb5849-0' and (text() = 'Desk Review' or . = 'Desk Review')]</value>
      <webElementGuid>8971e2d2-3a90-40db-a0f3-d2bc63d4fb71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
