<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consolidated ESEA Grants_ohio-checkbo_ec5fa3</name>
   <tag></tag>
   <elementGuidId>f057173b-44b8-4fef-a7ef-a6c8f02a2deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ohio-checkbox.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a0c16a1-ee19-43e4-aa54-35bd9af67962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1080daf4-dc3a-4bbb-9964-dac7a4a39b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ohio-checkbox ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>16be42d1-60b4-45af-ab97-8e918c4993ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/eas-core-application-container[1]/div[@class=&quot;exp-application&quot;]/div[@class=&quot;exp-content hide-spliter&quot;]/as-split[@class=&quot;as-horizontal as-pixel as-init&quot;]/as-split-area[@class=&quot;as-split-area&quot;]/div[@class=&quot;exp-panel&quot;]/div[@class=&quot;container-fluid&quot;]/app-meeting[1]/div[@class=&quot;table-display&quot;]/div[@class=&quot;container-fluid results-section&quot;]/div[@class=&quot;ohio-card ode-section clearfix&quot;]/eas-ui-lib-spinner[1]/div[@class=&quot;loader-page&quot;]/app-new-meeting[1]/div[@class=&quot;row fade-in&quot;]/div[@class=&quot;col-md-12&quot;]/ul[@class=&quot;form-list&quot;]/li[@class=&quot;meeting-checkbox&quot;]/div[@class=&quot;view-checkbox&quot;]/div[@class=&quot;ohio-checkbox&quot;]/input[@class=&quot;ohio-checkbox ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>b65b50fd-7670-4058-a9c9-d280d9249150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>b763507a-4155-4970-b190-9ae32536eb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/input</value>
      <webElementGuid>e943e93c-bfcb-431c-b58a-fe0cdd23a894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>babfabc3-6423-4658-888c-e8c543c1a152</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
