<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Monitoring</name>
   <tag></tag>
   <elementGuidId>50a8beea-d84a-4db1-9fdb-7030a52938e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(23) > td > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='emails']/tbody/tr[23]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d5692bb-33eb-4b14-b28a-faea46b30705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://monitoringqa.education.ohio.gov/?auth=qa</value>
      <webElementGuid>cdccaf32-2039-4e70-b7a2-d897f7aabaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monitoring</value>
      <webElementGuid>eb87158e-e047-4142-8858-66b52d08c15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emails&quot;)/tbody[@class=&quot;safe home&quot;]/tr[23]/td[1]/a[1]</value>
      <webElementGuid>fc3c8583-3141-47f6-9b40-304222e7735f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='emails']/tbody/tr[23]/td/a</value>
      <webElementGuid>426c2220-9331-4b64-87a4-afc12092c0c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Monitoring')]</value>
      <webElementGuid>64a58701-6c7c-476c-bfe1-cbe60d6c3b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grant Life Cycle'])[1]/following::a[1]</value>
      <webElementGuid>440c1a29-0289-4c67-a850-51beffc38aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grant Life Cycle - Dev'])[1]/following::a[1]</value>
      <webElementGuid>5c5a0307-962e-490a-a28c-4c4ef8c56473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring'])[2]/preceding::a[1]</value>
      <webElementGuid>6a53c056-1fb8-4ead-b961-8ee95c1d38e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring DEV'])[1]/preceding::a[1]</value>
      <webElementGuid>b646ece2-b921-4d01-8030-e9ce851c4652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monitoring']/parent::*</value>
      <webElementGuid>94b17fdb-a51f-4cc3-bd90-31efa0de4d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://monitoringqa.education.ohio.gov/?auth=qa')]</value>
      <webElementGuid>a444d4ce-1561-4272-a0dc-693d7cc040e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[23]/td/a</value>
      <webElementGuid>66a38ad6-130b-4f7f-bcef-728c4785e4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://monitoringqa.education.ohio.gov/?auth=qa' and (text() = 'Monitoring' or . = 'Monitoring')]</value>
      <webElementGuid>b8f0212a-3afd-427d-9166-119c5f4acd2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
