<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Monitoring</name>
   <tag></tag>
   <elementGuidId>fa3434fd-8c77-483a-ab57-f1436c9eee7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(20) > td > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='emails']/tbody/tr[20]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f56a6e32-1faf-45da-9a51-f728d2e5fb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://monitoringqa.education.ohio.gov/?auth=qa</value>
      <webElementGuid>6fd15175-fe43-4fc9-8f6b-0824d41aeaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monitoring</value>
      <webElementGuid>6213e78f-684a-4534-985b-42af83691787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emails&quot;)/tbody[@class=&quot;safe home&quot;]/tr[20]/td[1]/a[1]</value>
      <webElementGuid>b63a449a-7725-4a96-9fdb-099af8cd99a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='emails']/tbody/tr[20]/td/a</value>
      <webElementGuid>1237eaf5-b245-46c0-917b-32f687756c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Monitoring')]</value>
      <webElementGuid>0ee5e0f6-bac3-4acc-88f0-4b7071711db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning Management System'])[2]/following::a[1]</value>
      <webElementGuid>96e16349-c8b2-4adf-9b67-48b01d90b05c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning Management System'])[1]/following::a[1]</value>
      <webElementGuid>074d32f0-6f9f-4d37-9156-aba4efed204e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring'])[2]/preceding::a[1]</value>
      <webElementGuid>79f13958-3ed4-464d-81f8-48b3e17bbee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring DEV'])[1]/preceding::a[1]</value>
      <webElementGuid>e8034f86-6bdf-4217-8fe7-22b6537e1066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monitoring']/parent::*</value>
      <webElementGuid>083c479d-6422-4595-ac52-41d619cd5e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://monitoringqa.education.ohio.gov/?auth=qa')]</value>
      <webElementGuid>1f0d9144-8209-40ed-b9eb-9455c24c83b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td/a</value>
      <webElementGuid>aec2db64-d491-40d6-a864-eec5ebab3b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://monitoringqa.education.ohio.gov/?auth=qa' and (text() = 'Monitoring' or . = 'Monitoring')]</value>
      <webElementGuid>d969eb43-228e-4f1f-aa10-f796548a34a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
