<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forms Cloud</name>
   <tag></tag>
   <elementGuidId>16ef66e7-6d53-43af-9469-fe950c0f1a4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='emails']/tbody/tr[14]/td/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'https://safeqa.ode.state.oh.us/portal/?returnUrl=https://formsqa.education.ohio.gov' and (text() = 'Forms Cloud' or . = 'Forms Cloud')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(14) > td > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9cb98c77-16ef-41b1-88e4-74613d43748f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://safeqa.ode.state.oh.us/portal/?returnUrl=https://formsqa.education.ohio.gov</value>
      <webElementGuid>35656c93-c6b8-420c-a008-bf655f64a24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forms Cloud</value>
      <webElementGuid>85eacd35-69f5-4cba-acfd-7b3abb2576aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emails&quot;)/tbody[@class=&quot;safe home&quot;]/tr[14]/td[1]/a[1]</value>
      <webElementGuid>0cfd5d0d-313f-4d2b-a4c4-fe0139dff8e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='emails']/tbody/tr[14]/td/a</value>
      <webElementGuid>838ac791-8bdf-4ba1-b10c-bea4502aeb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forms Cloud')]</value>
      <webElementGuid>5df00586-0384-4ab3-9d52-1a1636495d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electronic Forms and Waiver Submission'])[1]/following::a[1]</value>
      <webElementGuid>7456523e-c968-4b96-ae85-c557f475803e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forms'])[1]/following::a[1]</value>
      <webElementGuid>52501bad-19ca-4776-8f70-b0684fa57197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forms Cloud'])[2]/preceding::a[1]</value>
      <webElementGuid>aa88547d-5289-409b-bae9-a3c203aa4a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forms Cloud DEV'])[1]/preceding::a[1]</value>
      <webElementGuid>d5fce35d-c3b8-420e-814c-0cc5ee569b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forms Cloud']/parent::*</value>
      <webElementGuid>d362f4b4-f48c-4c20-bf12-6a1dab6452dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://safeqa.ode.state.oh.us/portal/?returnUrl=https://formsqa.education.ohio.gov')]</value>
      <webElementGuid>b2d53178-cafb-4652-8bcc-a4ab9b7243c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td/a</value>
      <webElementGuid>eeba3443-20f5-485e-9255-e6b6d2d197e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://safeqa.ode.state.oh.us/portal/?returnUrl=https://formsqa.education.ohio.gov' and (text() = 'Forms Cloud' or . = 'Forms Cloud')]</value>
      <webElementGuid>288f3210-cb28-4b46-8044-d165002b113d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='emails']/tbody/tr[20]/td/a</value>
      <webElementGuid>37a93295-bda5-4dc4-893a-19e48498862d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td/a</value>
      <webElementGuid>2ca29704-2126-4600-8ef0-8b7e57ca4089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
