<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Charter School Program Grant</name>
   <tag></tag>
   <elementGuidId>a7383dea-26a1-437f-b462-abf96ed0c2c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#app_id_163</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='app_id_163']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7773000a-4676-4d2f-a3d9-5319f5d34a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_id_163</value>
      <webElementGuid>9d181889-172d-4fb9-a96b-fa65bda21b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charter School Program Grant</value>
      <webElementGuid>534ff922-b821-4126-a792-c6c58cda0b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_id_163&quot;)</value>
      <webElementGuid>1a93e2e8-d9a0-4ac6-b504-5bc1b7eb56a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='app_id_163']</value>
      <webElementGuid>9440dbf8-8457-4a55-9b5a-aa6fcb0b7b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Charter School Program Grant')]</value>
      <webElementGuid>0195b3c8-74d8-4033-8b62-a95fc1d70e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CCIP PCR FER Review'])[1]/following::a[1]</value>
      <webElementGuid>e447b2a6-53bf-4fe9-b463-518fe027ba77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annual Venereal Disease and Sexual Education Instruction Audit Program'])[1]/following::a[2]</value>
      <webElementGuid>fd95dd6c-6477-406f-9c6e-7722ba0a4d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community School Operator Agreement Self-Assessment'])[1]/preceding::a[1]</value>
      <webElementGuid>bc28d78d-3163-4875-9f10-d2c1fa19dac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community School Sponsorship'])[1]/preceding::a[2]</value>
      <webElementGuid>fb18969e-da11-48d8-ae35-b006b9d347fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Charter School Program Grant']/parent::*</value>
      <webElementGuid>cc2b8e61-3d93-4e3d-bb02-e0f7fbf8fb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>dab94cc8-98f3-40a3-8a2f-3f95e4429641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'app_id_163' and (text() = 'Charter School Program Grant' or . = 'Charter School Program Grant')]</value>
      <webElementGuid>1c11cb9f-1322-48f9-a47a-aacda1b2efac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
