<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_043802 - Columbus City Schools Distr_48b7a7</name>
   <tag></tag>
   <elementGuidId>94fae626-94d3-4cdf-9dac-d64745949deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ngb-typeahead-1-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ngb-typeahead-1-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5bea79e2-4894-42d8-b30e-4fb1c698e4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d76ee33f-8f5d-4505-b825-778970960e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item ng-tns-c85-1 ng-trigger ng-trigger-typeaheadAnimation ng-star-inserted active</value>
      <webElementGuid>bae56e08-40c2-49c1-a16c-5fab5532aed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ngb-typeahead-1-0</value>
      <webElementGuid>b12f2673-2694-4cd0-a01c-8a16da46555c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>043802 - Columbus City Schools District (Franklin)</value>
      <webElementGuid>fae61d09-fc1b-4f12-8750-0e20afb4a267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngb-typeahead-1-0&quot;)</value>
      <webElementGuid>155e883e-279e-477f-a843-d1308135e9e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ngb-typeahead-1-0']</value>
      <webElementGuid>2e5a3423-5a4e-457f-af4b-25aac4281415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//typeahead-container[@id='ngb-typeahead-1']/button</value>
      <webElementGuid>81745ed3-b2a6-4d2d-ac01-6a1f9a15c448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District IRN/Name'])[1]/following::button[1]</value>
      <webElementGuid>f2c97866-d515-4c6c-b742-0f39441fee20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Period'])[1]/following::button[1]</value>
      <webElementGuid>626419d4-ac56-4536-a3ec-b9043ea06def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building IRN/Name'])[1]/preceding::button[1]</value>
      <webElementGuid>bf8e81ea-2e05-4d4c-867f-3355150089fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//typeahead-container/button</value>
      <webElementGuid>b945daf0-6f63-4b55-a724-2b56bba7e1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ngb-typeahead-1-0' and (text() = '043802 - Columbus City Schools District (Franklin)' or . = '043802 - Columbus City Schools District (Franklin)')]</value>
      <webElementGuid>3daaee0a-e844-4c66-964f-ca6a2c1f0524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
