<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AnyNot Started</name>
   <tag></tag>
   <elementGuidId>e42d5963-397d-43fe-94bc-32aacf8696bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='surveyCompletionStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#surveyCompletionStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b8f72323-1639-435b-81ad-9f832eb37e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>surveyCompletionStatus</value>
      <webElementGuid>79ef4182-2aa6-4f6c-95f5-5bed76cd472a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>surveyCompletionStatus</value>
      <webElementGuid>e5412004-54bf-414a-a2a0-eafc177f7fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ohio-select-select-el ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>5c307257-c6d5-4288-b7cd-38f5d99011bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AnyNot StartedStartedIn ProgressSubmittedReviewedCompleted</value>
      <webElementGuid>1645bcc1-b462-4f33-bdc3-3f05c9d479b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;surveyCompletionStatus&quot;)</value>
      <webElementGuid>5389c7b6-de06-40b1-9f62-da901edc981f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='surveyCompletionStatus']</value>
      <webElementGuid>997c1bb4-5f74-41bb-a446-b9d96639004d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Survey Completion Status'])[1]/following::select[1]</value>
      <webElementGuid>4b50eca6-09ab-4bee-84d2-066e07ed361a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surveys'])[1]/following::select[2]</value>
      <webElementGuid>8deea025-2bf4-4c67-9a48-a3a431e8509a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Survey Compliance Status'])[1]/preceding::select[1]</value>
      <webElementGuid>67c1e12e-12d2-4914-8b14-7ef6f8942c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results Count'])[1]/preceding::select[2]</value>
      <webElementGuid>093c7abc-d107-462f-808e-cb4ae90d0348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-select-filter[4]/eas-ui-lib-form-group/label/span[2]/select</value>
      <webElementGuid>03236910-048c-4390-92a8-9e571411d7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'surveyCompletionStatus' and @name = 'surveyCompletionStatus' and (text() = 'AnyNot StartedStartedIn ProgressSubmittedReviewedCompleted' or . = 'AnyNot StartedStartedIn ProgressSubmittedReviewedCompleted')]</value>
      <webElementGuid>f6ca1e2d-d102-4870-869f-1ff3692cfa71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
