<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AnySurvey</name>
   <tag></tag>
   <elementGuidId>9c0514b2-9e0c-4924-8265-ec6fe648c923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='surveys']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#surveys</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e7e2277c-05ff-41c3-9bbb-038eae45bb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>surveys</value>
      <webElementGuid>2fae3292-c082-4e42-b72f-4e2e9e760f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>surveys</value>
      <webElementGuid>4c70264f-fff8-468e-923a-850fbe95ef3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ohio-select-select-el ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>8d329926-1930-4885-a07b-a8a41ac7d92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AnyFY 2024 CSP Grant Fall ReviewFY 2024 CSP Grant Fall ReviewFY 2024 CSP Grant Mid Year ReviewFY 2024 CSP Grant Final Review</value>
      <webElementGuid>3ec3e7aa-08b9-4dc8-99a0-2d445a5c1b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;surveys&quot;)</value>
      <webElementGuid>d01bc86d-65e8-4bcb-824a-94d6d21094ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='surveys']</value>
      <webElementGuid>ea0513ce-0e9b-49f4-990c-d4474b28bbaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surveys'])[1]/following::select[1]</value>
      <webElementGuid>a5185964-71bc-4ebc-947b-57b5cc89393a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overall Compliance Status'])[1]/following::select[2]</value>
      <webElementGuid>c65b1866-9fbc-47d9-8e58-9dc839b49ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Survey Completion Status'])[1]/preceding::select[1]</value>
      <webElementGuid>3505ec3c-23df-485e-8320-a878eed38e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Survey Compliance Status'])[1]/preceding::select[2]</value>
      <webElementGuid>c58a8d70-6dc9-4be9-9af7-5590c9df3f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-select-filter[3]/eas-ui-lib-form-group/label/span[2]/select</value>
      <webElementGuid>8502e21d-bb19-4071-8daa-ba9efd771d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'surveys' and @name = 'surveys' and (text() = 'AnyFY 2024 CSP Grant Fall ReviewFY 2024 CSP Grant Fall ReviewFY 2024 CSP Grant Mid Year ReviewFY 2024 CSP Grant Final Review' or . = 'AnyFY 2024 CSP Grant Fall ReviewFY 2024 CSP Grant Fall ReviewFY 2024 CSP Grant Mid Year ReviewFY 2024 CSP Grant Final Review')]</value>
      <webElementGuid>c644c633-989e-4a72-9de0-345dda8b96b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
