<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Emergency Medical Waiver</name>
   <tag></tag>
   <elementGuidId>6d8aefc1-56a7-42cd-b3ba-5f7dccd142d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#app_id_149</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='app_id_149']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>504f33ec-392b-489f-abe4-260088d8fdb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_id_149</value>
      <webElementGuid>4cc317ab-ac97-4c30-a786-48a4f55ee338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Emergency Medical Waiver</value>
      <webElementGuid>d4dd1bf8-5ef3-4e12-aeec-158987fc0624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_id_149&quot;)</value>
      <webElementGuid>39ba0349-3bfc-4e65-8531-297165b5cab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='app_id_149']</value>
      <webElementGuid>8a2e6b85-2631-4e9b-82ad-fa4f1cd1ef0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Emergency Medical Waiver')]</value>
      <webElementGuid>86b67e64-87e0-40ce-a4a0-460e4aa5fd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DPIA &amp; SWSF Data Collection Tool'])[1]/following::a[1]</value>
      <webElementGuid>8dcc84b5-8b3c-4438-be2f-a426f36b8117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Appeal'])[1]/following::a[2]</value>
      <webElementGuid>c941424d-35d0-43b3-b4c9-e0ca9e143afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMIS Data Review and Verification'])[1]/preceding::a[1]</value>
      <webElementGuid>03ec9b80-3800-43ae-b377-dee230699357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Equitable Access Plan'])[1]/preceding::a[2]</value>
      <webElementGuid>d7160e11-4a7c-4fc8-adfe-97edee043537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Emergency Medical Waiver']/parent::*</value>
      <webElementGuid>d4d7c8c5-54e9-4b65-8326-c6996b2e7bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a</value>
      <webElementGuid>66f99c19-932c-4be1-b30e-80e2e3cfa9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'app_id_149' and (text() = 'Emergency Medical Waiver' or . = 'Emergency Medical Waiver')]</value>
      <webElementGuid>a0cbe196-f731-4797-a0f6-d929bebcc16e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
