<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ODE View OnlyAdmin</name>
   <tag></tag>
   <elementGuidId>18ff36e9-2468-46db-b6d1-98a67d65ea4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#audience</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='audience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>17b18fc4-cb77-47e6-9a77-125d0f05993c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>audience</value>
      <webElementGuid>5cf99fba-7659-4492-85c1-cb22fa45fc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>audience</value>
      <webElementGuid>2520b890-464d-453a-89d0-104b9121d03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ohio-select-select-el ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>d080f1e8-0752-4c10-b748-844fb2300f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ODE View OnlyAdmin</value>
      <webElementGuid>0cfeacab-4814-47cc-b116-eb0158aa7304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;audience&quot;)</value>
      <webElementGuid>097b35ab-e3ed-458e-be63-96cfbac022c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='audience']</value>
      <webElementGuid>83809237-3c5b-4380-9aa6-9fb592b7ded6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View As'])[1]/following::select[1]</value>
      <webElementGuid>665d84bb-e147-4caa-8484-8cec9229fd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select A Program'])[1]/following::select[1]</value>
      <webElementGuid>b1ad41e1-58eb-4451-ba4b-3f40fc8f6622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Associated To'])[1]/preceding::select[1]</value>
      <webElementGuid>0cde627d-4c6d-40fc-91f5-036c92c8cf62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Advisory Councils'])[1]/preceding::select[1]</value>
      <webElementGuid>265bb08d-7d23-4b4f-b229-a6694ad66805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c0815415-54c2-46b9-bfe0-53a4bd20e13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'audience' and @id = 'audience' and (text() = 'ODE View OnlyAdmin' or . = 'ODE View OnlyAdmin')]</value>
      <webElementGuid>5d1aed30-e6c1-4691-a032-87d87dc78616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
