<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_District IRNName_district</name>
   <tag></tag>
   <elementGuidId>28f2780e-428c-47b7-9ff7-ab0369b64e62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'district' and @name = 'district']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='district']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>291a09e5-2508-480f-85b8-7680fa0c1291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>411238c2-0841-4634-ad89-52f32089e234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c44b67d8-9065-4494-a057-15fafe85f735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeaheadoptionslimit</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>422dce0a-4320-4b5b-9877-19bdf158b5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeaheadwaitms</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>370cd9c1-224d-4454-a191-8a3a424b1f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>ffc38dac-45b9-4c36-85a7-ba1c8ecb54df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>770c9105-7bae-4ca5-a396-8c38d8987ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead-min-length</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>02ad02d7-c296-4089-9956-3715576cf9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead-wait-ms</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>5039763f-e4be-4b6c-9996-b47f220f4f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead-options-limit</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>cccd4858-4823-45da-9ae4-8e64f99eb0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead-option-field</name>
      <type>Main</type>
      <value>fullName</value>
      <webElementGuid>242f89d0-0696-4db8-990b-f1a3719e1b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-typeahead-async</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b989deeb-88c3-4567-9992-c9a8a37b59e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ohio-field-input ng-dirty ng-touched ng-valid</value>
      <webElementGuid>b9c0e127-b559-4a22-b957-f9f46f136abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>district</value>
      <webElementGuid>056a82a1-1800-4a51-8846-d1837e5c6440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>district</value>
      <webElementGuid>a1894b94-dd9e-4962-a1e4-079c2b312cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;district&quot;)</value>
      <webElementGuid>78ac8cc6-eb8c-4e07-a8c7-66bba1ac4302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='district']</value>
      <webElementGuid>3dc10259-43cb-4aa7-88d2-5730bc821538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/app-search-container/div/div/app-search-form/div/div/eas-ui-lib-card/div/div/div/div/div/div/div/app-autocomplete-filter/eas-ui-lib-form-group/label/input</value>
      <webElementGuid>37c22109-07c6-4332-a864-303af1b984d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>488ec879-6b74-4f8e-89f8-a1b268706891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
